---
# tasks file for rthdev-keepalived
- block:

  - name: Install keepalived package
    yum:
      name: keepalived
      state: installed
    environment:
      http_proxy: "{{ rthar_keepalived_http_proxy | default(omit) }}"
      https_proxy: "{{ rthar_keepalived_https_proxy | default(omit) }}"
      no_proxy: "{{ rthar_keepalived_no_proxy | default(omit) }}"

  - name: Template out config
    template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
      owner: root
      group: root
      mode: 0640
    notify:
      - restart keepalived

  - meta: flush_handlers

  - name: Ensure keepalived service is running
    systemd:
      name: keepalived
      state: started
      enabled: true

  become: true
