---
# tasks file for rthar_nginx_server
- block:

  - name: Install packages
    ansible.builtin.yum:
      name: "{{ rthar_nginx_server_conf.packages }}"
      state: installed

  - name: Ensure SElinux requirements are met when managed
    yum:
      name: python3-policycoreutils
      state: installed
    when: rthar_nginx_server_conf.manage_firewall | bool
  
  - name: Ensure html directory is available
    ansible.builtin.file:
      path: "{{ rthar_nginx_server_conf.html_dir }}"
      owner: root
      group: root
      mode: 0755
      state: directory
  
  - name: Configure selinux if required
    community.general.sefcontext:
      target: '{{ rthar_nginx_server_conf.html_dir }}(/.*)?'
      setype: httpd_sys_rw_content_t
      state: present
    register: selinux_fcontext
    when: rthar_nginx_server_conf.manage_selinux | bool
  
  - name: Apply new SELinux file context to filesystem
    ansible.builtin.command:
      cmd: restorecon -irv "{{ rthar_nginx_server_conf.html_dir }}"
    when: selinux_fcontext.changed | bool
  
  - name: Template nginx configuration
    ansible.builtin.template:
      src: nginx.conf.j2
      dest: /etc/nginx/nginx.conf
      owner: root
      group: root
      mode: 0640
    register: config
  
  - name: Configure Firewall if required
    ansible.posix.firewalld:
      service: "{{ item }}"
      state: enabled
      immediate: true
      permanent: true
      zone: "{{ rthar_nginx_server_conf.firewall_zone }}"
    loop: "{{ rthar_nginx_server_conf.firewalld_services }}"
    when: rthar_nginx_server_conf.manage_firewall | bool
  
  - name: Restart service
    ansible.builtin.systemd:
      name: "{{ rthar_nginx_server_conf.systemd_service }}"
      state: started
    when: config.changed | bool
  
  - name: Enable and start service
    ansible.builtin.systemd:
      name: "{{ rthar_nginx_server_conf.systemd_service }}"
      state: started
      enabled: true

  become: true
  become_user: root
