---
# defaults file for rthar_dns_zone
rthar_dns_zone_config:
  config_serial: 2021100000
  config_refresh: 3600
  config_retry: 1800
  config_expire: 604800
  config_minttl: 86400
  fwd_name:
  rev_name:
  filename:
  nameserver:
  entries:
  dir: /var/named/domains
