---
# vars file for rthar_pxe_server
ks_centos7: http://infra.example.com/ks/centos7.ks

pxesrv_pxeconfig: "{{ pxesrv_tftproot }}/pxelinux.cfg/default"
pxesrv_services:
  - dhcpd
  - tftp.socket
  - tftp
  - vsftpd
pxesrv_pxefiles:
  - /usr/share/syslinux/pxelinux.0
  - /usr/share/syslinux/menu.c32
  - /usr/share/syslinux/mboot.c32
  - /usr/share/syslinux/chain.c32
  - /usr/share/syslinux/ldlinux.c32
  - /usr/share/syslinux/libutil.c32
  - /usr/share/syslinux/libcom32.c32
pxesrv_packages: 
  - dhcp-server
  - firewalld
  - tftp-server
  - vsftpd
  - syslinux
pxesrv_fw_services:
  - dhcp
  - proxy-dhcp
  - tftp
  - ftp
  - dns
