---
# defaults file for rthar_nginx_server
rthar_nginx_server_conf:
  html_dir: /var/www/html
  systemd_service: nginx
  firewalld_services:
    - https
  packages:
    - nginx
  manage_selinux: true
  manage_firewall: true
  firwall_zone: public
